server:
  port: 6788

logging:
  level.lab.zlren.mall.mapper: debug
  level: info

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckillmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 2
    id-type: 2
    refresh-mapper: false
  typeAliasesPackage: lab.zlren.mall.entity
