server:
  port: 6788

logging:
  level: info
  level.lab.zlren.mall.mapper: debug

spring:
  datasource:
    url: jdbc:mysql://10.108.114.166:3306/seckillmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: 10.109.246.70
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        max-concurrency: 10
        concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 2
    id-type: 2
    refresh-mapper: false
  typeAliasesPackage: lab.zlren.mall.entity

redis:
  host: 10.109.246.68
#  host: 118.89.227.189
  port: 6379
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

# static
spring.resources:
  add-mappings: true
  cache-period: 3600
  chain.cache: true
  chain.enabled: true
  chain.gzipped: true
  chain.html-application-cache: true
  static-locations: classpath:/static/