server:
  port: 6788

logging:
  level: error
  level.lab.zlren.mall.mapper: error

spring:
  datasource:
    url: jdbc:mysql://10.108.114.166:3306/seckillmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    field-strategy: 2
    id-type: 2
    refresh-mapper: false
  typeAliasesPackage: lab.zlren.mall.entity

redis:
  host: 10.109.246.68
#  host: 118.89.227.189
  port: 6379
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3
